sudo flatpak install flathub io.atom.Atom -y
sudo flatpak install flathub org.audacityteam.Audacity -y
sudo flatpak install flathub org.avidemux.Avidemux -y
sudo flatpak install flathub com.discordapp.Discord -y
sudo flatpak install flathub com.uploadedlobster.peek -y
sudo flatpak install flathub com.sublimetext.three -y
sudo flatpak install flathub com.vinszent.GnomeTwitch -y
sudo flatpak install flathub org.hydrogenmusic.Hydrogen -y
sudo flatpak install flathub org.kde.kdenlive -y
sudo flatpak install flathub com.obsproject.Studio -y
sudo flatpak install flathub org.pitivi.Pitivi -y
sudo flatpak install flathub com.spotify.Client -y
sudo flatpak install flathub com.stremio.Stremio -y
sudo flatpak install flathub org.videolan.VLC -y
sudo flatpak install flathub io.lmms.LMMS -y
sudo flatpak install flathub org.openshot.OpenShot -y
sudo flatpak install flathub org.apache.netbeans -y
sudo flatpak install flathub com.jetbrains.PyCharm-Community -y
sudo flatpak install flathub com.visualstudio.code -y
sudo flatpak install flathub com.vscodium.codium -y
sudo flatpak install flathub org.gnome.Glade -y
sudo flatpak install flathub io.github.shiftey.Desktop -y
sudo flatpak install flathub nl.hjdskes.gcolor3 -y
sudo flatpak install flathub org.gimp.GIMP -y
sudo flatpak install flathub org.inkscape.Inkscape -y
sudo flatpak install flathub com.github.libresprite.LibreSprite -y
sudo flatpak install flathub org.chromium.Chromium -y
sudo flatpak install flathub org.mozilla.firefox -y
sudo flatpak install flathub com.valvesoftware.Steam -y
sudo flatpak install flathub com.valvesoftware.SteamLink -y
sudo flatpak install flathub org.telegram.desktop -y
sudo flatpak install flathub nz.mega.MEGAsync -y
sudo flatpak install flathub com.github.bajoja.indicator-kdeconnect -y

